// Karma configuration
// Generated on Fri Sep 26 2014 17:24:21 GMT+0300 (EEST)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['mocha'],


    // list of files / patterns to load in the browser
    files: [
      'client/bower_components/should.js/should.js',
      'client/bower_components/jquery/dist/jquery.js',
      'client/bower_components/angular/angular.js',
      'client/bower_components/angular-mocks/angular-mocks.js',
      'client/bower_components/ngstorage/ngStorage.js',
      'client/bower_components/angular-ui-router/release/angular-ui-router.js',
      'client/bower_components/angular-animate/angular-animate.js',
      'client/bower_components/angular-cookies/angular-cookies.js',
      'client/bower_components/angular-gestures/gestures.js',
      'client/bower_components/angular-resource/angular-resource.js',
      'client/bower_components/angular-resource/angular-resource.js',
      'client/bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
      'client/bower_components/angular-sanitize/angular-sanitize.js',
      'client/bower_components/angular-ui-select/dist/select.js',
      'client/bower_components/angular-messages/angular-messages.js',
      'client/bower_components/angular-froala/src/angular-froala.js',
      'client/bower_components/angular-gridster/src/angular-gridster.js',
      'client/bower_components/tc-angular-chartjs/dist/tc-angular-chartjs.js',
      'client/bower_components/lodash/dist/lodash.js',
      "client/bower_components/sinon/index.js",
      'client/bower_components/angular-ui-slider/src/slider.js',
      "client/bower_components/angular-file-upload/angular-file-upload.min.js",
      "client/bower_components/angular-spectrum-colorpicker/dist/angular-spectrum-colorpicker.js",
      "client/bower_components/highcharts-ng/dist/highcharts-ng.js",
      "client/bower_components/highcharts-release/highcharts.src.js",
      "client/bower_components/Sortable/Sortable.js",
      "client/bower_components/Sortable/ng-sortable.js",
      'client/bower_components/angular-multirange-slider/src/multirange-slider.coffee',
      'client/bower_components/ng-slider/dist/ng-slider.min.js',
      'client/bower_components/angular-socket-io/socket.min.js',
      'client/bower_components/sio-client/socket.io.js',
      'client/bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js',
      // 'client/**/*.coffee',
      'client/**/*.jade',
      // inject-app
      './client/app/app.coffee',
      './client/app/settings.coffee',
      './client/app/404/404.coffee',
      './client/app/account/account.coffee',
      './client/app/admin/admin.coffee',
      './client/app/approve/approve.coffee',
      './client/app/approve/approve.controller.coffee',
      './client/app/approve/approve.service.coffee',
      './client/app/clients/clients.coffee',
      './client/app/clients/clients.controller.coffee',
      './client/app/clients/clients.service.coffee',
      './client/app/filearchive/filearchive.coffee',
      './client/app/filters/filesize.coffee',
      './client/app/filters/num.coffee',
      './client/app/filters/seconds.to.time.coffee',
      './client/app/filters/trust.html.coffee',
      './client/app/filters/trust.url.coffee',
      './client/app/filters/uppercaseNA.coffee',
      './client/app/main/main.coffee',
      './client/app/meeting/meeting.coffee',
      './client/app/meeting/meeting.controller.coffee',
      './client/app/my-board/my-board.coffee',
      './client/app/my-board/my-board.controller.coffee',
      './client/app/presentations/presentations.coffee',
      './client/app/presentations/presentations.controller.coffee',
      './client/app/reports/reports.coffee',
      './client/app/reports/reports.controller.coffee',
      './client/app/services/api.service.coffee',
      './client/app/services/file.upload.service.coffee',
      './client/app/services/socket.service.coffee',
      './client/app/users/users.coffee',
      './client/app/users/users.controller.coffee',
      './client/components/auth/auth.service.coffee',
      './client/components/auth/user.service.coffee',
      './client/components/directives/wmt.directives.coffee',
      './client/components/filters/wmt.filters.coffee',
      './client/components/form/compare-to.directive.coffee',
      './client/components/form/ensure-form-symbols.directives.coffee',
      './client/components/form/wmt-email-validation.directive.coffee',
      './client/components/froala-modifications/build-create-link.coffee',
      './client/components/froala-modifications/create-link-html.coffee',
      './client/components/froala-modifications/font-family.coffee',
      './client/components/froala-modifications/froala-video.coffee',
      './client/components/froala-modifications/insert-link.coffee',
      './client/components/froala-modifications/letter-spacing.coffee',
      './client/components/froala-modifications/line-height.coffee',
      './client/components/include-custom-fonts/include.custom.fonts.controller.coffee',
      './client/components/include-custom-fonts/include.custom.fonts.directive.coffee',
      './client/components/keyboard_processing/keypress.events.coffee',
      './client/components/navbar/navbar.controller.coffee',
      './client/components/navbar/navbar.derective.coffee',
      './client/components/navbar/navbar.derectives.coffee',
      './client/components/touch_processing/denied-scrolling.coffee',
      './client/app/account/login/login.controller.coffee',
      './client/app/account/reset-passwords/popover.directives.coffee',
      './client/app/account/reset-passwords/reset-passwords.controller.coffee',
      './client/app/account/send-reset-password/send-reset-password-controller.coffee',
      './client/app/admin/companies/admin.companies.coffee',
      './client/app/admin/companies/admin.companies.ctontroller.coffee',
      './client/app/clients/client-list/client.list.directive.coffee',
      './client/app/clients/client-list/clients-list-controller.coffee',
      './client/app/clients/client-profile/client-profile-controller.coffee',
      './client/app/clients/client-profile/client-profile.directive.coffee',
      './client/app/clients/view-presentation-all/view-presentation-all.coffee',
      './client/app/common/models/models.coffee',
      './client/app/filearchive/dialog/dialog.controller.coffee',
      './client/app/filearchive/dialog/dialog.file.archive.button.directive.coffee',
      './client/app/filearchive/dialog/dialog.file.archive.list.directive.coffee',
      './client/app/presentations/editor/editor.coffee',
      './client/app/presentations/editor/editor.controller.coffee',
      './client/app/presentations/presentations-list/presentations-list-manager.coffee',
      './client/app/presentations/services/edit-notes.service.coffee',
      './client/app/presentations/services/pptx-modal-switcher.service.coffee',
      './client/app/services/messenger/messenger.coffee',
      './client/app/users/services/user.presentations.service.coffee',
      './client/components/directives/bootstrap-spinedit/bootstrap-spinedit.directive.coffee',
      './client/components/directives/btn-edit/btn-edit.directive.coffee',
      './client/components/directives/checkbox/wmt-checkbox.directive.coffee',
      './client/components/directives/click-events/click.events.directive.coffee',
      './client/components/directives/content-limit-to/contentLimitTo.directive.coffee',
      './client/components/directives/custom.contenteditable/custom.contenteditable.directive.coffee',
      './client/components/directives/fade-in-visible/fade.in.visible.coffee',
      './client/components/directives/form-field-validation-marker/form.field.validation.marker.directive.coffee',
      './client/components/directives/form-save-button/form.save.button.directive.coffee',
      './client/components/directives/image-upload/imageonload.directive.coffee',
      './client/components/directives/image-upload/img.load.directive.coffee',
      './client/components/directives/include-replace/include-replace.directive.coffee',
      './client/components/directives/inline-tooltip/inline-tooltip.directive.coffee',
      './client/components/directives/keypress-events/wmt-keypress.directive.coffee',
      './client/components/directives/mousedown/wmt-mousedown.directive.coffee',
      './client/components/directives/numeric-format/numeric-format.coffee',
      './client/components/directives/open-presentation-preview/open.presentation.preview.directive.coffee',
      './client/components/directives/prz-image-loader/prz-image-loader-directive.coffee',
      './client/components/directives/scroll-top-by-change/scroll.top.by.change.directive.coffee',
      './client/components/directives/set-focus/wmt-focus.directive.coffee',
      './client/components/directives/ui-select-blur-token/ui-select-blur-token.directive.coffee',
      './client/components/directives/ui-select-combo-box/ui-select-combo-box.directive.coffee',
      './client/components/directives/ui-select-position/ui-select-position.directive.coffee',
      './client/components/directives/ui-select-search-focus/ui-select-search-focus.directive.coffee',
      './client/components/directives/ui-select-user-agent/ui-select-user-agent.directive.coffee',
      './client/components/directives/ui-slider-destroy/wmt-ui-slider-destroy.directive.coffee',
      './client/components/directives/uppercase/wmt-uppercase.directive.coffee',
      './client/components/directives/users-selecting/users-selecting.directive.coffee',
      './client/components/directives/valid-number/valid-number.coffee',
      './client/components/directives/wide-spinner/wide-spinner.coffee',
      './client/components/directives/wmt-square-selection/wmt-square-selection-directive.coffee',
      './client/components/filters/duration/duration.filter.coffee',
      './client/components/froala-modifications/plugins/background-color.coffee',
      './client/components/modules/animate/animate.coffee',
      './client/components/modules/wmt-gridster/gridster.coffee',
      './client/components/modules/wmt-gridster/gridster.directive.coffee',
      './client/components/modules/wmt-gridster/gridster.item.directive.coffee',
      './client/components/modules/wmt-image-editor/wmt.image.editor.directive.coffee',
      './client/components/modules/wmt-img-transform/wmt.img.transform.directive.coffee',
      './client/components/reports/email/email.report.controller.coffee',
      './client/components/reports/email/email.report.directive.coffee',
      './client/components/reports/meeting/meeting.report.controller.coffee',
      './client/components/reports/meeting/meeting.report.directive.coffee',
      './client/components/reports/presentation/presentation.report.controller.coffee',
      './client/components/reports/presentation/presentation.report.directive.coffee',
      './client/app/admin/companies/copy-presentation/admin.copy-presentation.controller.coffee',
      './client/app/admin/companies/edit/admin.companies.edit.ctontroller.coffee',
      './client/app/admin/store-services/companies/admin.companies.api.service.coffee',
      './client/app/admin/store-services/companies/admin.companies.fonts.service.coffee',
      './client/app/admin/store-services/companies/admin.companies.store.service.coffee',
      './client/app/admin/store-services/presentations/admin.presentations.api.service.coffee',
      './client/app/admin/store-services/presentations/admin.presentations.store.service.coffee',
      './client/app/admin/store-services/users/admin.users.api.service.coffee',
      './client/app/admin/store-services/users/admin.users.store.service.coffee',
      './client/app/clients/client-list/client-sessions-list/client.sessions.list.directive.coffee',
      './client/app/clients/clients-pop-up/create-meeting/create-meeting.coffee',
      './client/app/clients/clients-pop-up/create-meeting/open-create-meeting-dialog.directive.coffee',
      './client/app/clients/clients-pop-up/create-new-client/create_new_client.controller.coffee',
      './client/app/clients/clients-pop-up/create-new-client/open-create-client-dialog.directive.coffee',
      './client/app/clients/clients-pop-up/edit-client-detail/edit-client-detail.coffee',
      './client/app/clients/clients-pop-up/edit-client-detail/open-edit-client-dialog.directive.coffee',
      './client/app/clients/clients-pop-up/write-email/open-write-email-dialog.directive.coffee',
      './client/app/clients/clients-pop-up/write-email/write-email.coffee',
      './client/app/common/models/base-class/base-class.coffee',
      './client/app/common/models/clients/clients-model.coffee',
      './client/app/common/models/companies/companies-model.coffee',
      './client/app/common/models/emails/emails-model.coffee',
      './client/app/common/models/filearchive/filearchive-model.coffee',
      './client/app/common/models/lead-companies/lead-companies-model.coffee',
      './client/app/common/models/meetings/meetings-model.coffee',
      './client/app/common/models/pptx-converter/pptx-converter.api.service.coffee',
      './client/app/common/models/pptx-converter/pptx-converter.store.service.coffee',
      './client/app/common/models/presentations/presentation-defaults.coffee',
      './client/app/common/models/presentations/presentations-model.coffee',
      './client/app/common/models/reports/reports-factory.service.coffee',
      './client/app/common/models/reports/reports-model.coffee',
      './client/app/common/models/templates/templates-model.coffee',
      './client/app/common/models/users/users-model.coffee',
      './client/app/filearchive/components/breadcrumbs/file.archive.breadcrumbs.component.coffee',
      './client/app/filearchive/components/controls/filearchive-controls.component.coffee',
      './client/app/filearchive/components/controls/filearchive-controls.controller.coffee',
      './client/app/filearchive/components/list/filearchive-list.component.coffee',
      './client/app/filearchive/components/list/filearchive-list.controller.coffee',
      './client/app/filearchive/components/publish-files-modal/publish-files-modal.coffee',
      './client/app/filearchive/components/topbar/filearchive-topbar.component.coffee',
      './client/app/filearchive/components/topbar/filearchive-topbar.controller.coffee',
      './client/app/presentations/components/conversion-in-progress/conversion-in-progress.controller.coffee',
      './client/app/presentations/components/create-presentation-from-pptx/create-presentation-from-pptx.controller.coffee',
      './client/app/presentations/components/create-presentation-from-pptx/open-create-presentation-from-pptx-dialog.directive.coffee',
      './client/app/presentations/components/import-slides-from-pptx/import-slides-from-pptx.controller.coffee',
      './client/app/presentations/components/iport-and-convert-pptx/iport-and-convert-pptx.controller.coffee',
      './client/app/presentations/directives/edit-notes/edit-notes.directive.coffee',
      './client/app/presentations/directives/editors-modal/edit-modal.controller.coffee',
      './client/app/presentations/directives/publish-modal/publish-modal.coffee',
      './client/app/presentations/directives/selecting-users/wmt-selecting-users.directive.coffee',
      './client/app/presentations/editor/edit/edit.coffee',
      './client/app/presentations/editor/edit/edit.controller.coffee',
      './client/app/presentations/editor/history/history.coffee',
      './client/app/presentations/editor/history/history.controller.coffee',
      './client/app/presentations/editor/menu/menu.coffee',
      './client/app/presentations/editor/menu/menu.controller.coffee',
      './client/app/presentations/editor/preview/preview.coffee',
      './client/app/presentations/editor/preview/preview.controller.coffee',
      './client/app/presentations/editor/slidetree/slidetree.coffee',
      './client/app/presentations/editor/slidetree/slidetree.controller.coffee',
      './client/app/presentations/editor/templates/templates.coffee',
      './client/app/presentations/editor/templates/templates.controller.coffee',
      './client/app/presentations/editor/widgets/calculation-content.directive.coffee',
      './client/app/presentations/editor/widgets/text.content.area.directive.coffee',
      './client/app/presentations/presentations-list/controls/presentations.list.controls.directive.coffee',
      './client/app/presentations/presentations-list/list/presentations.list.directive.coffee',
      './client/app/reports/components/reports-view-panel/reports-view-panel.component.coffee',
      './client/app/reports/components/top-bar-controls/top-bar-controls.component.coffee',
      './client/app/users/components/controls/users-controls.component.coffee',
      './client/app/users/components/controls/users-controls.controller.coffee',
      './client/app/users/components/edit-user/edit.user.directive.coffee',
      './client/app/users/components/form/users-form.controller.coffee',
      './client/app/users/components/list/users-list.component.coffee',
      './client/app/users/components/list/users-list.controller.coffee',
      './client/app/users/components/manage-country-department-team/manage-country-department-team.coffee',
      './client/app/users/components/manage-country-department-team/open-manage-country-department-team-dialog.directive.coffee',
      './client/app/users/components/topbar/users-topbar.component.coffee',
      './client/app/users/components/topbar/users-topbar.controller.coffee',
      './client/components/modules/wmt-gridster/controllers/gridster.controller.coffee',
      './client/components/modules/wmt-gridster/controllers/gridster.item.controller.coffee',
      './client/components/modules/wmt-gridster/services/gridster.draggable.service.coffee',
      './client/components/modules/wmt-gridster/services/gridster.resizable.service.coffee',
      './client/components/modules/wmt-image-editor/classes/crop.area.coffee',
      './client/components/modules/wmt-image-editor/classes/crop.area.square.coffee',
      './client/components/modules/wmt-image-editor/classes/crop.canvas.coffee',
      './client/components/modules/wmt-image-editor/classes/transform.host.coffee',
      './client/components/modules/wmt-image-editor/classes/transform.image.coffee',
      './client/components/modules/wmt-image-editor/classes/transform.pubsub.coffee',
      './client/components/modules/wmt-img-transform/classes/crop.area.circle.coffee',
      './client/components/modules/wmt-img-transform/classes/crop.area.coffee',
      './client/components/modules/wmt-img-transform/classes/crop.area.square.coffee',
      './client/components/modules/wmt-img-transform/classes/crop.canvas.coffee',
      './client/components/modules/wmt-img-transform/classes/transform.host.coffee',
      './client/components/modules/wmt-img-transform/classes/transform.image.coffee',
      './client/components/modules/wmt-img-transform/classes/transform.pubsub.coffee',
      './client/app/admin/companies/components/companies-controls/admin.companies.controls.component.coffee',
      './client/app/admin/companies/components/companies-list/admin.companies.list.component.coffee',
      './client/app/clients/clients-pop-up/create-meeting/agenda-edit/agenda.edit.directive.coffee',
      './client/app/clients/clients-pop-up/create-meeting/agenda-edit-link/agenda.edit.link.directive.coffee',
      './client/app/common/models/base-class/base/base.coffee',
      './client/app/common/models/base-class/cacheable/cacheable.coffee',
      './client/app/common/models/base-class/extendable/extendable.coffee',
      './client/app/common/models/base-class/mocks/mocks.coffee',
      './client/app/common/models/base-class/mocks/presentation.coffee',
      './client/app/common/models/base-class/observeable/observeable.coffee',
      './client/app/common/models/presentations/chapter/chapter.service.coffee',
      './client/app/common/models/presentations/configurations/content.configurations.service.coffee',
      './client/app/common/models/presentations/content/content.factory.coffee',
      './client/app/common/models/presentations/content/content.service.coffee',
      './client/app/common/models/presentations/image/image-model.coffee',
      './client/app/common/models/presentations/slide/public-presentations-model.coffee',
      './client/app/common/models/presentations/slide/slide.service.coffee',
      './client/app/presentations/editor/common/services/color-picker-palette.service.coffee',
      './client/app/presentations/editor/common/services/state.from.to.servise.coffee',
      './client/app/presentations/editor/common/slide-calculator/slide-calculator.directive.coffee',
      './client/app/presentations/editor/common/slide-default/slide-default.directive.coffee',
      './client/app/presentations/editor/common/topbar-controls/topbar-controls.directive.coffee',
      './client/app/presentations/editor/edit/controls/edit-controls.controller.coffee',
      './client/app/presentations/editor/edit/side-menu/side-menu.directive.coffee',
      './client/app/presentations/editor/edit/slide-psg/slide.psg.directive.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/top-menu-controls.component.coffee',
      './client/app/presentations/editor/menu/controls/menu-controls.controller.coffee',
      './client/app/presentations/editor/preview/controls/preview.controls.controller.coffee',
      './client/app/presentations/editor/slidetree/controls/slidetree-controls-switcher.directive.coffee',
      './client/app/presentations/editor/slidetree/directives/gridster-auto-size.directive.coffee',
      './client/app/presentations/editor/slidetree/services/gridster-draggable-mock.factory.coffee',
      './client/app/presentations/editor/slidetree/services/slidetree-helper.service.coffee',
      './client/app/presentations/editor/templates/controls/template-controls.controller.coffee',
      './client/app/presentations/editor/widgets/bubbles-content-area/bubbles-content-area-directive.coffee',
      './client/app/presentations/editor/widgets/classic-slider/classic-slider.coffee',
      './client/app/presentations/editor/widgets/color-picker/color.picker.directive.coffee',
      './client/app/presentations/editor/widgets/flat-color-picker/flat.color.picker.directive.coffee',
      './client/app/presentations/editor/widgets/hotspot/hotspot.directive.coffee',
      './client/app/presentations/editor/widgets/image-content-area/image.content.area.directive.coffee',
      './client/app/presentations/editor/widgets/image-widget/image-widget.coffee',
      './client/app/presentations/editor/widgets/numeric-input/numeric-input.directive.coffee',
      './client/app/presentations/editor/widgets/pz-slider/pz-slider.coffee',
      './client/app/reports/components/reports-view-panel/filter-controls/filter-controls.component.coffee',
      './client/app/reports/components/reports-view-panel/reports-list/reports-list.controller.coffee',
      './client/app/reports/components/top-bar-controls/reports-type-select/reports-type-select.component.coffee',
      './client/app/users/components/form/access-rights/access-rights.component.coffee',
      './client/app/users/components/form/access-rights/access-rights.controller.coffee',
      './client/app/users/components/form/manage-user-presentations/manage.user.presentations.directive.coffee',
      './client/app/users/components/form/tabs-form/tabs-form.component.coffee',
      './client/app/users/components/form/user-profile/current-user-profile.component.coffee',
      './client/app/users/components/form/user-profile/user-profile.component.coffee',
      './client/app/users/components/form/user-profile/user-profile.controller.coffee',
      './client/app/users/components/manage-country-department-team/manage-country/manage-country.component.coffee',
      './client/app/users/components/manage-country-department-team/manage-country/manage-country.controller.coffee',
      './client/app/users/components/manage-country-department-team/manage-department/manage-department.component.coffee',
      './client/app/users/components/manage-country-department-team/manage-department/manage-department.controller.coffee',
      './client/app/users/components/manage-country-department-team/manage-team/manage-team.component.coffee',
      './client/app/users/components/manage-country-department-team/manage-team/manage-team.controller.coffee',
      './client/app/admin/companies/edit/components/control-buttons/edit-control-buttons.component.coffee',
      './client/app/admin/companies/edit/components/layout/admin.companies.edit.layout.component.coffee',
      './client/app/admin/companies/edit/components/profile/admin.companies.edit.profile.component.coffee',
      './client/app/common/models/presentations/content/models/bubble-model.service.coffee',
      './client/app/common/models/presentations/content/models/calculation-model.service.coffee',
      './client/app/common/models/presentations/content/models/graph-model.service.coffee',
      './client/app/common/models/presentations/content/models/hotspot-model.service.coffee',
      './client/app/common/models/presentations/content/models/image-model.service.coffee',
      './client/app/common/models/presentations/content/models/input-model.service.coffee',
      './client/app/common/models/presentations/content/models/layer-model.service.coffee',
      './client/app/common/models/presentations/content/models/psg-content-model.service.coffee',
      './client/app/common/models/presentations/content/models/slider-model.service.coffee',
      './client/app/common/models/presentations/content/models/table-model.service.coffee',
      './client/app/common/models/presentations/content/models/text-model.service.coffee',
      './client/app/common/models/presentations/content/models/video-model.service.coffee',
      './client/app/presentations/editor/common/directives/build-area/buildarea.directive.coffee',
      './client/app/presentations/editor/common/directives/dead-link-spot/dead.link.spot.directive.coffee',
      './client/app/presentations/editor/common/directives/dead-wideo-spot/dead.wideo.spot.directive.coffee',
      './client/app/presentations/editor/common/directives/default-prz-css/default-prz-css.directive.coffee',
      './client/app/presentations/editor/common/directives/gridster/gridster-centred.coffee',
      './client/app/presentations/editor/common/directives/hotspot-image-dialog/hotspot-image-dialog.directive.coffee',
      './client/app/presentations/editor/common/directives/hotspot-rich-text-dialog/hotspot.rich.text.dialog.directive.coffee',
      './client/app/presentations/editor/common/directives/responsive/responsive.view.directives.coffee',
      './client/app/presentations/editor/common/directives/slide-background-area/slide-background-area.component.coffee',
      './client/app/presentations/editor/common/directives/slide-navigate-arrows/slide-navigate-arrows.directive.coffee',
      './client/app/presentations/editor/common/directives/slide-navigation/slide-navigation.directive.coffee',
      './client/app/presentations/editor/common/directives/slide-navigation-panel/slide.navigation.panel.directive.coffee',
      './client/app/presentations/editor/common/directives/text.content.render/text.content.render.directive.coffee',
      './client/app/presentations/editor/common/directives/widget-link-icon/widget-link-icon.component.coffee',
      './client/app/presentations/editor/common/services/calculator-helper/calculator-helper.service.coffee',
      './client/app/presentations/editor/common/services/math-parser/math-parser.service.coffee',
      './client/app/presentations/editor/common/slide-calculator/flexi-grid/flexi-grid.component.coffee',
      './client/app/presentations/editor/edit/controls/add-content/add-content.directive.coffee',
      './client/app/presentations/editor/edit/controls/bubbles/edit-bubbles-directive.coffee',
      './client/app/presentations/editor/edit/controls/bubbles/edit-bubbles-service.coffee',
      './client/app/presentations/editor/edit/controls/calculation/calculation-controls.component.coffee',
      './client/app/presentations/editor/edit/controls/chart/chart-type-menu.directive.coffee',
      './client/app/presentations/editor/edit/controls/chart/edit-chart-menu-switcher.directive.coffee',
      './client/app/presentations/editor/edit/controls/chart/edit-chart-menu-switcher.service.coffee',
      './client/app/presentations/editor/edit/controls/color-picker/wmt-color-picker.component.coffee',
      './client/app/presentations/editor/edit/controls/hotspot/edit-hotspot-controls.directive.coffee',
      './client/app/presentations/editor/edit/controls/hotspot/hotspot-icon-service.coffee',
      './client/app/presentations/editor/edit/controls/hotspot/hotspot.service.coffee',
      './client/app/presentations/editor/edit/controls/image/edit-image-controls.component.coffee',
      './client/app/presentations/editor/edit/controls/image/edit.image.controller.coffee',
      './client/app/presentations/editor/edit/controls/image/image-editor-controls.service.coffee',
      './client/app/presentations/editor/edit/controls/image-widget/image-widget-controls.component.coffee',
      './client/app/presentations/editor/edit/controls/link-builder/link-builder.component.coffee',
      './client/app/presentations/editor/edit/controls/link-editor/link.editor.directive.coffee',
      './client/app/presentations/editor/edit/controls/plain-text/edit-font-size.component.coffee',
      './client/app/presentations/editor/edit/controls/plain-text/edit-font-type.component.coffee',
      './client/app/presentations/editor/edit/controls/plain-text/edit-text-alignment.component.coffee',
      './client/app/presentations/editor/edit/controls/second-layer/second-layer.coffee',
      './client/app/presentations/editor/edit/controls/side-menu-image-selector/side-menu-image-selector.directive.coffee',
      './client/app/presentations/editor/edit/controls/slide-background-editor/slide.background.editor.directive.coffee',
      './client/app/presentations/editor/edit/controls/slider/custom-slider-service.coffee',
      './client/app/presentations/editor/edit/controls/slider/edit-pz-slider-controls.directive.coffee',
      './client/app/presentations/editor/edit/controls/slider/edit-slider-controls.directive.coffee',
      './client/app/presentations/editor/edit/controls/table/edit.table.directive.coffee',
      './client/app/presentations/editor/edit/controls/table/edit.table.service.coffee',
      './client/app/presentations/editor/edit/controls/text/edit.text.controller.coffee',
      './client/app/presentations/editor/edit/controls/text/edit.text.service.coffee',
      './client/app/presentations/editor/edit/controls/video/edit.video.directive.coffee',
      './client/app/presentations/editor/edit/default-slide/area-background-color-picker/area-background-color-picker.directive.coffee',
      './client/app/presentations/editor/edit/default-slide/content-type-menu/content-type-menu-button.directive.coffee',
      './client/app/presentations/editor/edit/default-slide/content-type-menu/content-type-menu.directive.coffee',
      './client/app/presentations/editor/edit/default-slide/graph.content/graph.content.directive.coffee',
      './client/app/presentations/editor/edit/default-slide/margins-editor/margins-editor.directive.coffee',
      './client/app/presentations/editor/edit/default-slide/table.content/table.content.directive.coffee',
      './client/app/presentations/editor/edit/default-slide/video.content/video.content.directive.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/copy-content-button/copy-cotent-button.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-bg-color/edit-content-bg-color.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-border/edit-content-border.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-border-color/edit-content-border-color.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-decimals-number/edit-content-decimals-number.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-font-color/edit-content-font-color.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-font-family/edit-content-font-family.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-font-size/edit-content-font-size.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-font-style/edit-content-font-style.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-font-underline/edit-content-font-underline.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-font-weight/edit-content-font-weight.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-link/edit-content-link.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/edit-content-text-alignment/edit-content-text-alignment.component.coffee',
      './client/app/presentations/editor/edit/top-menu-controls/remove-content-button/remove-content-button.coffee',
      './client/app/presentations/editor/menu/controls/link-menu/link.menu.editor.directive.coffee',
      './client/app/presentations/editor/menu/controls/link-menu-item/link.menu.item.editor.directive.coffee',
      './client/app/presentations/editor/preview/devises/laptop/laptop.coffee',
      './client/app/presentations/editor/preview/devises/laptop/laptop.controller.coffee',
      './client/app/presentations/editor/preview/devises/tablet/tablet.coffee',
      './client/app/presentations/editor/preview/devises/tablet/tablet.controller.coffee',
      './client/app/presentations/editor/slidetree/controls/edit-app-icon/edit-app-icon-model.coffee',
      './client/app/presentations/editor/slidetree/controls/edit-app-icon/edit-app-icon.directive.coffee',
      './client/app/presentations/editor/slidetree/controls/slidetree-controls/slidetree-controls.directive.coffee',
      './client/app/reports/components/reports-view-panel/reports-list/emails/reports-emails-list.component.coffee',
      './client/app/reports/components/reports-view-panel/reports-list/meetings/reports-meetings-list.component.coffee',
      './client/app/reports/components/reports-view-panel/reports-list/presentations/reports-presentations-list.component.coffee',
      './client/app/users/components/form/directives/password-validation-error-messages/password.validation.error.messages.directive.coffee',
      './client/app/users/components/form/manage-user-presentations/user-presentations-list/user-presentations-list-manager.coffee',
      './client/app/presentations/editor/common/directives/slide-navigation-panel/language-list/language.list.directive.coffee',
      './client/app/presentations/editor/common/directives/slide-navigation-panel/slide_navigation_chapter_bur/slide.navigation.chapter.bur.directive.coffee',
      './client/app/presentations/editor/edit/controls/chart/column/edit-chart.directive.coffee',
      './client/app/presentations/editor/edit/controls/chart/column/edit-column.directive.coffee',
      './client/app/presentations/editor/edit/controls/chart/line/edit-line-chart.directive.coffee',
      './client/app/presentations/editor/edit/controls/chart/line/edit-line.directive.coffee',
      './client/app/presentations/editor/edit/controls/chart/pie/edit-pie-chart.directive.coffee',
      './client/app/presentations/editor/edit/controls/chart/pie/edit-pie.directive.coffee',
      './client/app/presentations/editor/edit/controls/slide-background-editor/file-archive-image-selector/file.archive.image.selector.directive.coffee',
      './client/app/presentations/editor/edit/controls/text/text-link-editor/text.link.editor.directive.coffee',
      './client/app/reports/components/reports-view-panel/reports-list/directives/enhanced-report/enhanced.report.directive.coffee',
      './client/app/reports/components/reports-view-panel/reports-list/directives/report-list-scroll/report.list.scroll.directive.coffee',
      './client/app/reports/components/reports-view-panel/reports-list/directives/responsive-height-box/responsive-height-box.directive.coffee',
      './client/app/users/components/form/manage-user-presentations/user-presentations-list/controls/user.presentations.list.controls.directive.coffee',
      './client/app/users/components/form/manage-user-presentations/user-presentations-list/list/user.presentations.list.directive.coffee',
      './client/app/admin/companies/edit/components/layout/components/font-uploader/font-uploader-component.coffee',
      './client/app/presentations/editor/edit/controls/slide-background-editor/file-archive-image-selector/file.archive.image.selector.popover/file.archive.image.selector.popover.directive.coffee'
      // endinject-app
      ,'client/**/*.spec.coffee',
      'client/test/*.json'
    ],


    // list of files to exclude
    exclude: [
      './client/components/froala-modifications/font-family.coffee',
      './client/components/froala-modifications/froala-video.coffee',
      './client/components/froala-modifications/insert-link.coffee',
      './client/components/froala-modifications/build-create-link.coffee',
      './client/components/froala-modifications/create-link-html.coffee',
      './client/components/froala-modifications/line-height.coffee',
      './client/components/froala-modifications/letter-spacing.coffee',
      './client/components/froala-modifications/plugins/background-color.coffee'
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      '**/*.coffee': ['coffee'],
      '**/*.jade': ['ng-jade2js'],
      '**/*.json': ['ng-json2js']
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress','junit'],
    junitReporter: {
      outputFile: 'test_reports/karma-test-results.xml',
      suite: ''
    },
    ngJade2JsPreprocessor: {
      stripPrefix: 'client/',
      prependPrefix: '/',
      moduleName: 'clientTemplates'
    },
    ngJson2JsPreprocessor: {
      stripPrefix: 'client/test/',
      prependPrefix: 'served/'
    },

    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  });
};
